// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    "intro",
    {
      type: "category",
      label: "System Administration",
      items: [
        // "tutorial-intro",
        {
          type: "category",
          label: "Debian",
          items: [
            {
              type: "autogenerated",
              dirName: "sysadmin/debian",
            },
          ],
        },
        {
          type: "category",
          label: "AAPanel",
          items: [
            {
              type: "autogenerated",
              dirName: "sysadmin/aapanel",
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "List",
      items: [
        {
          type: "autogenerated",
          dirName: "list",
        },
      ],
    },
  ],
};

module.exports = sidebars;
